from __future__ import annotations

from httpflow import __version__
from httpflow.runtime.mask import _MASK_DEFAULTS

from .analysis import GenerateOptions, WorkflowAnalysis
from .names import env_name
from .runtime import base_helpers, capture_helpers, http_helpers, until_helpers
from .shell import default_assignment, mask_key_pattern


class ScriptRenderer:
    """Render the final standalone bash script."""

    def render(
        self,
        analysis: WorkflowAnalysis,
        step_blocks: list[str],
        calls: list[str],
        *,
        generated_at: str,
        options: GenerateOptions,
    ) -> str:
        """Return the complete generated bash script."""
        shebang_line = "#!/usr/bin/env bash\n"

        # Build default variable assignments
        default_lines: list[str] = []
        default_vars = dict(options.default_vars or {})
        if default_vars:
            for k, v in sorted(default_vars.items()):
                default_lines.append(default_assignment(env_name("VAR", k), v))

        defaults_block = "\n".join(default_lines)
        if defaults_block:
            defaults_block = f"\n# ─── defaults (can be overridden by exporting beforehand) ───────────\n{defaults_block}\n"

        required_vars_block = self._required_var_check(analysis.required_vars)

        mask_keys_default = "|".join(sorted(_MASK_DEFAULTS))
        bash_mask_keys_default = mask_key_pattern(mask_keys_default)

        header = f"""{shebang_line}# Generated by toml-http-flow {__version__} at {generated_at}
set -uo pipefail

# Dependencies
curl --version >/dev/null || {{ echo "curl is required" >&2; exit 1; }}
{('jq --version >/dev/null || { echo "jq is required for JSON capture" >&2; exit 1; }' if analysis.needs_jq else '')}
{base_helpers(bash_mask_keys_default)}
{capture_helpers() if analysis.has_capture else ''}
{http_helpers(analysis.has_capture)}
{until_helpers() if analysis.has_until else ''}
{defaults_block}
{required_vars_block}"""

        if step_blocks:
            funcs = "\n\n".join(step_blocks)
            calls_src = "\n".join(calls)
        else:
            funcs = "# (no steps)"
            calls_src = "    :  # no steps"

        script = f"""{header}
# ─── step functions ─────────────────────────────────────────────────

{funcs}

# ─── main ───────────────────────────────────────────────────────────
main() {{
    for arg in "$@"; do
        case "$arg" in
            --pretty-json)
                HTTPFLOW_PRETTY_JSON=1
                ;;
            -h|--help)
                echo "usage: $0 [--pretty-json]"
                exit 0
                ;;
            *)
                echo "error: unknown argument: $arg" >&2
                exit 1
                ;;
        esac
    done
    export HTTPFLOW_PRETTY_JSON=${{HTTPFLOW_PRETTY_JSON:-}}

    HF_TMPDIR=$(mktemp -d) || {{
        echo "error: failed to create temporary directory" >&2
        exit 1
    }}
    export HF_TMPDIR
    trap 'rm -rf -- "$HF_TMPDIR"' EXIT SIGINT
{calls_src}
}}

main "$@"
"""
        return script

    @staticmethod
    def _required_var_check(names: tuple[str, ...]) -> str:
        """Emit bash statements that fail when required VAR_* values are empty."""
        if not names:
            return ""
        lines = ["", "# ─── required variables ──────────────────────────────────────────────"]
        for name in names:
            env = env_name("VAR", name)
            lines.extend([
                f'if [ -z "${{{env}:-}}" ]; then',
                f'    echo "error: missing required variable: {name}" >&2',
                f'    echo "Export it before running: export {env}=<value>" >&2',
                "    exit 1",
                "fi",
            ])
        lines.append("")
        return "\n".join(lines)
