from __future__ import annotations

from httpflow import __version__
from httpflow.runtime.mask import _MASK_DEFAULTS

from .analysis import GenerateOptions, WorkflowAnalysis
from .names import env_name
from .runtime import base_helpers, capture_helpers, http_helpers, until_helpers
from .shell import default_assignment, mask_key_pattern


class ScriptRenderer:
    """Render the final standalone bash script."""

    def render(
        self,
        analysis: WorkflowAnalysis,
        step_blocks: list[str],
        calls: list[str],
        *,
        generated_at: str,
        options: GenerateOptions,
    ) -> str:
        """Return the complete generated bash script."""
        shebang_line = "#!/usr/bin/env bash\n"

        # Build default variable assignments
        default_lines: list[str] = []
        default_vars = dict(options.default_vars or {})
        if default_vars:
            for k, v in sorted(default_vars.items()):
                default_lines.append(default_assignment(env_name("VAR", k), v))

        defaults_block = "\n".join(default_lines)
        if defaults_block:
            defaults_block = f"\n# ─── defaults (can be overridden by exporting beforehand) ───────────\n{defaults_block}\n"

        required_vars_block = self._required_var_check(analysis.required_vars, indent="    ")

        mask_keys_default = "|".join(sorted(_MASK_DEFAULTS))
        bash_mask_keys_default = mask_key_pattern(mask_keys_default)

        include_b64decode = bool(analysis.embedded_files)
        embedded_decls: list[str] = []
        for ef in analysis.embedded_files:
            embedded_decls.append(f"readonly __HF_EMBED_{ef.var_name}={self._b64_str_literal(ef.b64_content)}")
        embedded_block = "\n".join(embedded_decls)
        if embedded_block:
            embedded_block = f"\n# ─── embedded files (base64) ─────────────────────────────────────\n{embedded_block}\n"

        header = f"""{shebang_line}# Generated by toml-http-flow {__version__} at {generated_at}
set -uo pipefail

# Dependencies
curl --version >/dev/null || {{ echo "curl is required" >&2; exit 1; }}
{('jq --version >/dev/null || { echo "jq is required for JSON capture" >&2; exit 1; }' if analysis.needs_jq else '')}
{base_helpers(bash_mask_keys_default, include_b64decode=include_b64decode)}
{capture_helpers() if analysis.has_capture else ''}
{http_helpers(expose_body_log=analysis.needs_body_log_var)}
{until_helpers() if analysis.has_until else ''}
{defaults_block}
{embedded_block}"""

        if step_blocks:
            funcs = "\n\n".join(step_blocks)
            calls_src = "\n".join(calls)
        else:
            funcs = "# (no steps)"
            calls_src = "    :  # no steps"

        script = f"""{header}
# ─── step functions ─────────────────────────────────────────────────

{funcs}

# ─── main ───────────────────────────────────────────────────────────
main() {{
    local arg var_name var_value
    while (( $# > 0 )); do
        arg=$1
        case "$arg" in
            --pretty-json)
                HTTPFLOW_PRETTY_JSON=1
                ;;
            --no-mask)
                HTTPFLOW_NO_MASK=1
                ;;
            --blank-line)
                if (( $# < 2 )); then
                    echo "error: --blank-line requires a non-negative integer argument" >&2
                    exit 1
                fi
                HTTPFLOW_BLANK_LINE=$2
                shift
                ;;
            --blank-line=*)
                HTTPFLOW_BLANK_LINE=${{arg#--blank-line=}}
                ;;
            -h|--help)
                cat <<'__HF_HELP__'
usage: <script> [options] [--<name> <value>]...

options:
  --pretty-json      pretty-print JSON request/response bodies
  --no-mask          disable masking of sensitive fields
  --blank-line N     separate step log output with N blank lines
  -h, --help         show this help

variable injection:
  --<name> <value>           set VAR_<NAME> (uppercased, '-' -> '_')
  --<name>=<value>           same, with inline value
  Example: --option-a value  ->  VAR_OPTION_A=value
           (referenced in the flow as ${{VAR_OPTION_A}})
__HF_HELP__
                exit 0
                ;;
            --?*)
                # Generic variable injection:
                #   --<name> <value>   sets VAR_<NAME> (name uppercased, '-' -> '_')
                #   --<name>=<value>   same, with inline value
                # Reserved flags above (--pretty-json / --no-mask / --blank-line /
                # --help) are matched first; a flow variable that collides with one
                # of those names can still be set via the '--<name>=<value>' form.
                if [[ "$arg" == *=* ]]; then
                    var_name=${{arg#--}}
                    var_name=${{var_name%%=*}}
                    var_value=${{arg#*=}}
                else
                    if (( $# < 2 )); then
                        echo "error: $arg requires a value argument" >&2
                        exit 1
                    fi
                    var_name=${{arg#--}}
                    var_value=$2
                    shift
                fi
                if [[ ! "$var_name" =~ ^[A-Za-z0-9_-]+$ ]]; then
                    echo "error: invalid variable name '$var_name' from arg '$arg'" >&2
                    exit 1
                fi
                var_name=${{var_name//-/_}}
                var_name=$(printf '%s' "$var_name" | awk '{{print toupper($0)}}')
                printf -v "VAR_$var_name" '%s' "$var_value"
                ;;
            *)
                echo "error: unknown argument: $arg" >&2
                exit 1
                ;;
        esac
        shift
    done
    export HTTPFLOW_PRETTY_JSON=${{HTTPFLOW_PRETTY_JSON:-}}
    export HTTPFLOW_NO_MASK=${{HTTPFLOW_NO_MASK:-}}
    export HTTPFLOW_BLANK_LINE=${{HTTPFLOW_BLANK_LINE:-0}}
    case "$HTTPFLOW_BLANK_LINE" in
        ''|*[!0-9]*)
            echo "error: --blank-line / HTTPFLOW_BLANK_LINE must be a non-negative integer, got: $HTTPFLOW_BLANK_LINE" >&2
            exit 1
            ;;
    esac
{required_vars_block}
    HF_TMPDIR=$(mktemp -d) || {{
        echo "error: failed to create temporary directory" >&2
        exit 1
    }}
    export HF_TMPDIR
    trap 'rm -rf -- "$HF_TMPDIR"' EXIT SIGINT
{calls_src}
}}

main "$@"
"""
        return script

    @staticmethod
    def _required_var_check(names: tuple[str, ...], *, indent: str = "") -> str:
        """Emit bash statements that fail when required VAR_* values are empty.

        *indent* is prepended to every line so the block can be placed inside
        ``main()`` (after argument parsing) instead of running at top level —
        this lets ``--<name> <value>`` CLI args satisfy required variables.
        """
        if not names:
            return ""
        lines = ["", "# ─── required variables ──────────────────────────────────────────────"]
        for name in names:
            env = env_name("VAR", name)
            lines.extend([
                f'[[ -z "${{{env}:-}}" ]] && {{',
                f'    echo "error: missing required variable: {name}" >&2',
                f'    echo "Export it before running: export {env}=<value>" >&2',
                "    exit 1",
                "}",
            ])
        lines.append("")
        if indent:
            lines = [f"{indent}{ln}" if ln else ln for ln in lines]
        return "\n".join(lines)

    @staticmethod
    def _b64_str_literal(s: str) -> str:
        """Return a bash single-quoted literal for a base64 string (no special chars except ')."""
        return "'" + s.replace("'", "'\"'\"'") + "'"
